/*
* generated by Xtext
*/
package featureSeqDiag.sdedit;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SD_languageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return featureSeqDiag.sdedit.ui.internal.SD_languageActivator.getInstance().getInjector("featureSeqDiag.sdedit.SD_language");
	}
	
}
