/*
 * generated by Xtext
 */
package sdedit;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SDELangRuntimeModule extends sdedit.AbstractSDELangRuntimeModule {

}
