/**
 * generated by Xtext
 */
package sdedit.validation;

import sdedit.validation.AbstractSDELangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SDELangValidator extends AbstractSDELangValidator {
}
