/*
 * generated by Xtext
 */
package featureSeqDiag.sdcombin.ui.contentassist

import featureSeqDiag.sdcombin.ui.contentassist.AbstractSDC_languageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SDC_languageProposalProvider extends AbstractSDC_languageProposalProvider {
}
