/**
 * generated by Xtext
 */
package featureSeqDiag.sdedit.validation;

import featureSeqDiag.sdedit.validation.AbstractSD_languageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SD_languageValidator extends AbstractSD_languageValidator {
}
