/**
 * generated by Xtext
 */
package featureSeqDiag.sdcombin.validation;

import featureSeqDiag.sdcombin.validation.AbstractSDC_languageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SDC_languageValidator extends AbstractSDC_languageValidator {
}
