/*
 * generated by Xtext
 */
package sdedit.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import sdedit.ui.internal.SDELangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SDELangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SDELangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SDELangActivator.getInstance().getInjector(SDELangActivator.SDEDIT_SDELANG);
	}
	
}
