/**
 * generated by Xtext
 */
package featureSeqDiag.sdedit.ui.contentassist;

import featureSeqDiag.sdedit.ui.contentassist.AbstractSD_languageProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SD_languageProposalProvider extends AbstractSD_languageProposalProvider {
}
