/*
* generated by Xtext
*/
package sdcombin.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sdcombin.services.SDCLangGrammarAccess;

public class SDCLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SDCLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected sdcombin.parser.antlr.internal.InternalSDCLangParser createParser(XtextTokenStream stream) {
		return new sdcombin.parser.antlr.internal.InternalSDCLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SequenceProg";
	}
	
	public SDCLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SDCLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
