/*
* generated by Xtext
*/
package featureSeqDiag.sdedit.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SD_languageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("featureSeqDiag/sdedit/parser/antlr/internal/InternalSD_language.tokens");
	}
}
