/*
 * generated by Xtext
 */
package featureSeqDiag.sdedit;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SD_languageRuntimeModule extends featureSeqDiag.sdedit.AbstractSD_languageRuntimeModule {

}
