/*
 * generated by Xtext
 */
package sdcombin.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSDCLangValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(sdcombin.sDCLang.SDCLangPackage.eINSTANCE);
		return result;
	}
}
