/**
 * generated by Xtext
 */
package sdcombin.validation;

import sdcombin.validation.AbstractSDCLangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SDCLangValidator extends AbstractSDCLangValidator {
}
