/*
 * generated by Xtext
 */
package featureSeqDiag.sdcombin.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSDC_languageValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(featureSeqDiag.sdcombin.sDC_language.SDC_languagePackage.eINSTANCE);
		return result;
	}
}
