/*
* generated by Xtext
*/
package sdedit;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SDELangUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return sdedit.ui.internal.SDELangActivator.getInstance().getInjector("sdedit.SDELang");
	}
	
}
