/*
 * generated by Xtext
 */
package featureSeqDiag.sdcombin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SDC_languageUiModule extends featureSeqDiag.sdcombin.ui.AbstractSDC_languageUiModule {
	public SDC_languageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
