/**
 * generated by Xtext
 */
package sdedit.ui.contentassist;

import sdedit.ui.contentassist.AbstractSDELangProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SDELangProposalProvider extends AbstractSDELangProposalProvider {
}
