/*
 * generated by Xtext
 */
package sdedit.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SDELangUiModule extends sdedit.ui.AbstractSDELangUiModule {
	public SDELangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
