/**
 * generated by Xtext
 */
package sdcombin.ui.contentassist;

import sdcombin.ui.contentassist.AbstractSDCLangProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SDCLangProposalProvider extends AbstractSDCLangProposalProvider {
}
