/*
 * generated by Xtext
 */
package featureSeqDiag.sdedit.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSD_languageValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(featureSeqDiag.sdedit.sD_language.SD_languagePackage.eINSTANCE);
		return result;
	}
}
