/*
 * generated by Xtext
 */
package featureSeqDiag.sdedit.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import featureSeqDiag.sdedit.ui.internal.SD_languageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SD_languageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SD_languageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SD_languageActivator.getInstance().getInjector(SD_languageActivator.FEATURESEQDIAG_SDEDIT_SD_LANGUAGE);
	}
	
}
