/*
* generated by Xtext
*/
package sdedit;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SDELangStandaloneSetup extends SDELangStandaloneSetupGenerated{

	public static void doSetup() {
		new SDELangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

