/*
 * generated by Xtext
 */
package featureSeqDiag.sdcombin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SDC_languageRuntimeModule extends featureSeqDiag.sdcombin.AbstractSDC_languageRuntimeModule {

}
