/*
* generated by Xtext
*/
package featureSeqDiag.sdcombin;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SDC_languageStandaloneSetup extends SDC_languageStandaloneSetupGenerated{

	public static void doSetup() {
		new SDC_languageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

