/*
 * generated by Xtext
 */
package featureSeqDiag.sdedit.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SD_languageUiModule extends featureSeqDiag.sdedit.ui.AbstractSD_languageUiModule {
	public SD_languageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
